Fix unescaped strings in generated renderdoc trace code
Some strings used in traces contain characters such as '\' which need to
be properly escaped during generation of C++ code. Otherwise the
generated code doesn't compile. An example of compilation error is this:

  gen_create_7.cpp:9945:43: warning: unknown escape sequence '\m'
  /*pObjectName=*/ "models\npc\orcs\materials\head_14\orc_head14_m.tex",
                                   ^

Change-Id: I5caf015cd9cdbe8f22fa7bd4a08c04e8100be75c